# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ssorgatem/Documents/python/Qwad/GUI/VenPri.ui'
#
# Created: Sat Jul 25 02:02:42 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Qwad(object):
    def setupUi(self, Qwad):
        Qwad.setObjectName("Qwad")
        Qwad.resize(481, 296)
        Qwad.setMinimumSize(QtCore.QSize(481, 296))
        Qwad.setMaximumSize(QtCore.QSize(481, 296))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/wad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Qwad.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(Qwad)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 481, 251))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setObjectName("tabWidget")
        self.unpacktab = QtGui.QWidget()
        self.unpacktab.setObjectName("unpacktab")
        self.MuestraRutaWad = QtGui.QLineEdit(self.unpacktab)
        self.MuestraRutaWad.setGeometry(QtCore.QRect(160, 40, 241, 26))
        self.MuestraRutaWad.setObjectName("MuestraRutaWad")
        self.BotonRutaWad = QtGui.QToolButton(self.unpacktab)
        self.BotonRutaWad.setGeometry(QtCore.QRect(70, 40, 91, 25))
        self.BotonRutaWad.setObjectName("BotonRutaWad")
        self.MuestraRutaExtraer = QtGui.QLineEdit(self.unpacktab)
        self.MuestraRutaExtraer.setGeometry(QtCore.QRect(160, 110, 241, 26))
        self.MuestraRutaExtraer.setObjectName("MuestraRutaExtraer")
        self.BotonRutaExtraer = QtGui.QToolButton(self.unpacktab)
        self.BotonRutaExtraer.setGeometry(QtCore.QRect(70, 110, 91, 25))
        self.BotonRutaExtraer.setAutoRaise(False)
        self.BotonRutaExtraer.setArrowType(QtCore.Qt.NoArrow)
        self.BotonRutaExtraer.setObjectName("BotonRutaExtraer")
        self.Desempaqueta = QtGui.QPushButton(self.unpacktab)
        self.Desempaqueta.setGeometry(QtCore.QRect(170, 180, 121, 25))
        self.Desempaqueta.setObjectName("Desempaqueta")
        self.tabWidget.addTab(self.unpacktab, "")
        self.packtab = QtGui.QWidget()
        self.packtab.setObjectName("packtab")
        self.MuestraRutaEmpaquetado = QtGui.QLineEdit(self.packtab)
        self.MuestraRutaEmpaquetado.setGeometry(QtCore.QRect(160, 110, 241, 26))
        self.MuestraRutaEmpaquetado.setObjectName("MuestraRutaEmpaquetado")
        self.MuestraRutaDesempaquetado = QtGui.QLineEdit(self.packtab)
        self.MuestraRutaDesempaquetado.setGeometry(QtCore.QRect(160, 40, 241, 26))
        self.MuestraRutaDesempaquetado.setObjectName("MuestraRutaDesempaquetado")
        self.BotonRutaEmpaquetado = QtGui.QToolButton(self.packtab)
        self.BotonRutaEmpaquetado.setGeometry(QtCore.QRect(70, 110, 91, 25))
        self.BotonRutaEmpaquetado.setAutoRaise(False)
        self.BotonRutaEmpaquetado.setArrowType(QtCore.Qt.NoArrow)
        self.BotonRutaEmpaquetado.setObjectName("BotonRutaEmpaquetado")
        self.BotonRutaDesempaquetado = QtGui.QToolButton(self.packtab)
        self.BotonRutaDesempaquetado.setGeometry(QtCore.QRect(70, 40, 91, 25))
        self.BotonRutaDesempaquetado.setObjectName("BotonRutaDesempaquetado")
        self.Empaqueta = QtGui.QPushButton(self.packtab)
        self.Empaqueta.setGeometry(QtCore.QRect(170, 180, 121, 25))
        self.Empaqueta.setObjectName("Empaqueta")
        self.tabWidget.addTab(self.packtab, "")
        self.NUStab = QtGui.QWidget()
        self.NUStab.setObjectName("NUStab")
        self.NusOutputPath = QtGui.QLineEdit(self.NUStab)
        self.NusOutputPath.setGeometry(QtCore.QRect(140, 150, 241, 26))
        self.NusOutputPath.setObjectName("NusOutputPath")
        self.Download_from_NUS = QtGui.QPushButton(self.NUStab)
        self.Download_from_NUS.setGeometry(QtCore.QRect(170, 180, 121, 25))
        self.Download_from_NUS.setObjectName("Download_from_NUS")
        self.NusOutputButton = QtGui.QToolButton(self.NUStab)
        self.NusOutputButton.setGeometry(QtCore.QRect(40, 150, 91, 25))
        self.NusOutputButton.setAutoRaise(False)
        self.NusOutputButton.setArrowType(QtCore.Qt.NoArrow)
        self.NusOutputButton.setObjectName("NusOutputButton")
        self.enteredTitleID = QtGui.QLineEdit(self.NUStab)
        self.enteredTitleID.setGeometry(QtCore.QRect(125, 45, 161, 31))
        self.enteredTitleID.setObjectName("enteredTitleID")
        self.TitleIDlabel = QtGui.QLabel(self.NUStab)
        self.TitleIDlabel.setGeometry(QtCore.QRect(15, 51, 101, 20))
        self.TitleIDlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.TitleIDlabel.setObjectName("TitleIDlabel")
        self.Title = QtGui.QLabel(self.NUStab)
        self.Title.setGeometry(QtCore.QRect(0, 10, 121, 21))
        self.Title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Title.setObjectName("Title")
        self.comboBox = QtGui.QComboBox(self.NUStab)
        self.comboBox.setGeometry(QtCore.QRect(125, 10, 291, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.decryptCheck = QtGui.QCheckBox(self.NUStab)
        self.decryptCheck.setEnabled(False)
        self.decryptCheck.setGeometry(QtCore.QRect(130, 80, 171, 23))
        self.decryptCheck.setChecked(False)
        self.decryptCheck.setObjectName("decryptCheck")
        self.pack_in_WAD_checkbox = QtGui.QCheckBox(self.NUStab)
        self.pack_in_WAD_checkbox.setGeometry(QtCore.QRect(130, 110, 181, 23))
        self.pack_in_WAD_checkbox.setChecked(True)
        self.pack_in_WAD_checkbox.setObjectName("pack_in_WAD_checkbox")
        self.VersionlineEdit = QtGui.QLineEdit(self.NUStab)
        self.VersionlineEdit.setGeometry(QtCore.QRect(340, 45, 71, 31))
        self.VersionlineEdit.setObjectName("VersionlineEdit")
        self.versionlabel = QtGui.QLabel(self.NUStab)
        self.versionlabel.setGeometry(QtCore.QRect(290, 50, 51, 20))
        self.versionlabel.setObjectName("versionlabel")
        self.tabWidget.addTab(self.NUStab, "")
        Qwad.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Qwad)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 481, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        Qwad.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(Qwad)
        self.statusBar.setObjectName("statusBar")
        Qwad.setStatusBar(self.statusBar)
        self.actionAcerca_de_Qwad = QtGui.QAction(Qwad)
        self.actionAcerca_de_Qwad.setIcon(icon)
        self.actionAcerca_de_Qwad.setObjectName("actionAcerca_de_Qwad")
        self.actionAbout_Qt = QtGui.QAction(Qwad)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/qt4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon1)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_Wii_Signer = QtGui.QAction(Qwad)
        self.actionAbout_Wii_Signer.setObjectName("actionAbout_Wii_Signer")
        self.menuAyuda.addAction(self.actionAcerca_de_Qwad)
        self.menuAyuda.addAction(self.actionAbout_Qt)
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(Qwad)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Qwad)

    def retranslateUi(self, Qwad):
        Qwad.setWindowTitle(QtGui.QApplication.translate("Qwad", "Qwad - a WAD management tool", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaWad.setToolTip(QtGui.QApplication.translate("Qwad", "Ruta hacia el archivo WAD que quieres desempaquetar", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaWad.setText(QtGui.QApplication.translate("Qwad", "WAD file", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaExtraer.setToolTip(QtGui.QApplication.translate("Qwad", "Carpeta donde se almacenaran los contenidos del archivo WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaExtraer.setText(QtGui.QApplication.translate("Qwad", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.Desempaqueta.setText(QtGui.QApplication.translate("Qwad", "Unpack", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.unpacktab), QtGui.QApplication.translate("Qwad", "Unpack WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaEmpaquetado.setToolTip(QtGui.QApplication.translate("Qwad", "Carpeta y nombre del nuevo WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaEmpaquetado.setText(QtGui.QApplication.translate("Qwad", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaDesempaquetado.setToolTip(QtGui.QApplication.translate("Qwad", "Ruta hacia la carpeta que empaquetar en WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaDesempaquetado.setText(QtGui.QApplication.translate("Qwad", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.Empaqueta.setText(QtGui.QApplication.translate("Qwad", "Pack", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.packtab), QtGui.QApplication.translate("Qwad", "Pack WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.Download_from_NUS.setText(QtGui.QApplication.translate("Qwad", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.NusOutputButton.setToolTip(QtGui.QApplication.translate("Qwad", "Carpeta y nombre del nuevo WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.NusOutputButton.setText(QtGui.QApplication.translate("Qwad", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.enteredTitleID.setText(QtGui.QApplication.translate("Qwad", "000000000000000000", None, QtGui.QApplication.UnicodeUTF8))
        self.TitleIDlabel.setText(QtGui.QApplication.translate("Qwad", "Title ID", None, QtGui.QApplication.UnicodeUTF8))
        self.Title.setText(QtGui.QApplication.translate("Qwad", "Choose title:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Qwad", "Custom title ID", None, QtGui.QApplication.UnicodeUTF8))
        self.decryptCheck.setText(QtGui.QApplication.translate("Qwad", "Decrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.pack_in_WAD_checkbox.setText(QtGui.QApplication.translate("Qwad", "Pack into WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.VersionlineEdit.setText(QtGui.QApplication.translate("Qwad", "unset", None, QtGui.QApplication.UnicodeUTF8))
        self.versionlabel.setText(QtGui.QApplication.translate("Qwad", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NUStab), QtGui.QApplication.translate("Qwad", "Download from NUS", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("Qwad", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de_Qwad.setText(QtGui.QApplication.translate("Qwad", "About Qwad", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("Qwad", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Wii_Signer.setText(QtGui.QApplication.translate("Qwad", "About Wii Signer", None, QtGui.QApplication.UnicodeUTF8))

import Qwad_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Qwad = QtGui.QMainWindow()
    ui = Ui_Qwad()
    ui.setupUi(Qwad)
    Qwad.show()
    sys.exit(app.exec_())

