# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ssorgatem/Documents/python/Qwad/GUI/VenPri.ui'
#
# Created: Mon Jul 20 14:25:51 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Qwad(object):
    def setupUi(self, Qwad):
        Qwad.setObjectName("Qwad")
        Qwad.resize(351, 222)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/wad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Qwad.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(Qwad)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 351, 201))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.MuestraRutaWad = QtGui.QLineEdit(self.tab)
        self.MuestraRutaWad.setGeometry(QtCore.QRect(90, 10, 241, 26))
        self.MuestraRutaWad.setObjectName("MuestraRutaWad")
        self.BotonRutaWad = QtGui.QToolButton(self.tab)
        self.BotonRutaWad.setGeometry(QtCore.QRect(0, 10, 91, 25))
        self.BotonRutaWad.setObjectName("BotonRutaWad")
        self.MuestraRutaExtraer = QtGui.QLineEdit(self.tab)
        self.MuestraRutaExtraer.setGeometry(QtCore.QRect(90, 90, 241, 26))
        self.MuestraRutaExtraer.setObjectName("MuestraRutaExtraer")
        self.BotonRutaExtraer = QtGui.QToolButton(self.tab)
        self.BotonRutaExtraer.setGeometry(QtCore.QRect(0, 90, 91, 25))
        self.BotonRutaExtraer.setAutoRaise(False)
        self.BotonRutaExtraer.setArrowType(QtCore.Qt.NoArrow)
        self.BotonRutaExtraer.setObjectName("BotonRutaExtraer")
        self.Desempaqueta = QtGui.QPushButton(self.tab)
        self.Desempaqueta.setGeometry(QtCore.QRect(110, 130, 121, 25))
        self.Desempaqueta.setObjectName("Desempaqueta")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.updateTMD = QtGui.QCheckBox(self.tab_3)
        self.updateTMD.setEnabled(True)
        self.updateTMD.setGeometry(QtCore.QRect(20, 50, 121, 23))
        self.updateTMD.setChecked(True)
        self.updateTMD.setObjectName("updateTMD")
        self.MuestraRutaEmpaquetado = QtGui.QLineEdit(self.tab_3)
        self.MuestraRutaEmpaquetado.setGeometry(QtCore.QRect(90, 90, 241, 26))
        self.MuestraRutaEmpaquetado.setObjectName("MuestraRutaEmpaquetado")
        self.MuestraRutaDesempaquetado = QtGui.QLineEdit(self.tab_3)
        self.MuestraRutaDesempaquetado.setGeometry(QtCore.QRect(90, 10, 241, 26))
        self.MuestraRutaDesempaquetado.setObjectName("MuestraRutaDesempaquetado")
        self.BotonRutaEmpaquetado = QtGui.QToolButton(self.tab_3)
        self.BotonRutaEmpaquetado.setGeometry(QtCore.QRect(0, 90, 91, 25))
        self.BotonRutaEmpaquetado.setAutoRaise(False)
        self.BotonRutaEmpaquetado.setArrowType(QtCore.Qt.NoArrow)
        self.BotonRutaEmpaquetado.setObjectName("BotonRutaEmpaquetado")
        self.BotonRutaDesempaquetado = QtGui.QToolButton(self.tab_3)
        self.BotonRutaDesempaquetado.setGeometry(QtCore.QRect(0, 10, 91, 25))
        self.BotonRutaDesempaquetado.setObjectName("BotonRutaDesempaquetado")
        self.Empaqueta = QtGui.QPushButton(self.tab_3)
        self.Empaqueta.setGeometry(QtCore.QRect(110, 130, 121, 25))
        self.Empaqueta.setObjectName("Empaqueta")
        self.tabWidget.addTab(self.tab_3, "")
        Qwad.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Qwad)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 351, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        Qwad.setMenuBar(self.menuBar)
        self.actionAcerca_de_Qwad = QtGui.QAction(Qwad)
        self.actionAcerca_de_Qwad.setIcon(icon)
        self.actionAcerca_de_Qwad.setObjectName("actionAcerca_de_Qwad")
        self.actionAbout_Qt = QtGui.QAction(Qwad)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/qt4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon1)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_Wii_Signer = QtGui.QAction(Qwad)
        self.actionAbout_Wii_Signer.setObjectName("actionAbout_Wii_Signer")
        self.menuAyuda.addAction(self.actionAcerca_de_Qwad)
        self.menuAyuda.addAction(self.actionAbout_Qt)
        self.menuAyuda.addAction(self.actionAbout_Wii_Signer)
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(Qwad)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Qwad)

    def retranslateUi(self, Qwad):
        Qwad.setWindowTitle(QtGui.QApplication.translate("Qwad", "Qwad - Empaquetador y desempaquetador de WADs", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaWad.setToolTip(QtGui.QApplication.translate("Qwad", "Ruta hacia el archivo WAD que quieres desempaquetar", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaWad.setText(QtGui.QApplication.translate("Qwad", "Archivo WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaExtraer.setToolTip(QtGui.QApplication.translate("Qwad", "Carpeta donde se almacenaran los contenidos del archivo WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaExtraer.setText(QtGui.QApplication.translate("Qwad", "Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.Desempaqueta.setText(QtGui.QApplication.translate("Qwad", "Desempaquetar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Qwad", "Desempaquetar", None, QtGui.QApplication.UnicodeUTF8))
        self.updateTMD.setToolTip(QtGui.QApplication.translate("Qwad", "Sólo necesario en caso de que hayas modificado el WAD original", None, QtGui.QApplication.UnicodeUTF8))
        self.updateTMD.setText(QtGui.QApplication.translate("Qwad", "Actualizar TMD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaEmpaquetado.setToolTip(QtGui.QApplication.translate("Qwad", "Carpeta y nombre del nuevo WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaEmpaquetado.setText(QtGui.QApplication.translate("Qwad", "Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaDesempaquetado.setToolTip(QtGui.QApplication.translate("Qwad", "Ruta hacia la carpeta que empaquetar en WAD", None, QtGui.QApplication.UnicodeUTF8))
        self.BotonRutaDesempaquetado.setText(QtGui.QApplication.translate("Qwad", "Carpeta", None, QtGui.QApplication.UnicodeUTF8))
        self.Empaqueta.setText(QtGui.QApplication.translate("Qwad", "Empaquetar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Qwad", "Empaquetar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("Qwad", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de_Qwad.setText(QtGui.QApplication.translate("Qwad", "Acerca de Qwad", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("Qwad", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Wii_Signer.setText(QtGui.QApplication.translate("Qwad", "About Wii Signer", None, QtGui.QApplication.UnicodeUTF8))

import Qwad_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Qwad = QtGui.QMainWindow()
    ui = Ui_Qwad()
    ui.setupUi(Qwad)
    Qwad.show()
    sys.exit(app.exec_())

